### ISSUE TITLE
No RDMA Write sync and faulty byte order conversion

### ISSUE THREAD

**Issue by Kerby92** [w180112/RDMA-example#3]
There are two current existing issues to report here:

1.  When client is posting the RDMA Write operation to write data to remote memory of server, the server gets no feedback about when the RDMA Write operation is finished. As a result, the server could likely process the line 188 in rdma_write_server.c
`buf[0] = htonl(ntohl(buf[0]) + ntohl(buf[1]));`
faster than the client can write the user-defined numbers to this memory. Potential solution: Add a RDMA send operation to sync server and client.

2. Line 166 in rdma_write_server.c:
`rep_pdata.buf_va = htonl((uintptr_t)buf); `
You need `htonll()` because `.buf_va` is 64 bytes defined.
Line 210 in rdma_write_client.c:
`send_wr.wr.rdma.remote_addr   = ntohl(server_pdata.buf_va);`
You need `ntohll()` because `.remote_addr` is 64 bytes defined.

**Comment by w180112** [comment]
Hi @Kerby92,
Thanks for suggestion! These are already applied in https://github.com/w180112/RDMA-example/commit/6efd145bec48f13ac6424dbb074cb81f4f10e38a.

BR,
